version: "3.9"

services:
  loki:
    image: grafana/loki:2.1.0
    container_name: loki
    command: -config.file=/mnt/loki-local-config.yaml
    user: root
    restart: unless-stopped
    volumes:
      - loki_data:/tmp/loki
      - ./config.yml:/mnt/loki-local-config.yaml
    ports:
      - 3100:3100
    networks:
      - internal
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        fluentd-async-connect: "true"
        tag: service.loki

volumes:
  loki_data:
