services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command: "--config.file=/tmp/prometheus.yml --web.listen-address '0.0.0.0:9090'"
    ports:
      - 9090:9090
    networks:
      - internal
    volumes:
      - ./config.yml:/tmp/prometheus.yml
    depends_on:
      statsd-exporter: { condition: service_started }
      cadvisor: { condition: service_started }
    labels:
      caddy: prom.dev.vasandani.me
      caddy.handle_path: /*
      caddy.handle_path.reverse_proxy: "{{ upstreams 9090 }}"
      caddy.tls: internal
      logging: promtail
      logging_jobname: containerlogs
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        fluentd-async-connect: 'true'
        tag: service.prometheus

