# my global config
global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: statsd-exporter
    metrics_path: '/metrics'
    static_configs:
      - targets: ['statsd-exporter:9102']
        labels:
          exporter: 'statsd'

  - job_name: node-exporter
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          exporter: 'node'

  - job_name: elasticsearch-exporter
    metrics_path: '/metrics'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
        labels:
          exporter: 'elasticsearch'

  - job_name: postgres-exporter
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          exporter: 'postgres'

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
