version: '3.9'

services:
    # TODO install custom root certificates
  caddy:
    container_name: caddy
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 2019:2019
      - 2020:2020
    networks:
      - external
      - internal
    environment:
      CADDY_INGRESS_NETWORKS: internal
      CADDY_DOCKER_NO_SCOPE: true
      CADDY_DOCKER_CADDYFILE_PATH: /data/caddy/files/Caddyfile
      CLOUDFLARE_EMAIL: david@vasandani.me
    volumes:
      - ./certs:/data/caddy/pki/authorities/local/
      - ./:/data/caddy/files
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - ../../tests/php-fpm/src/:/php-fpm-root/php-test
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        fluentd-async-connect: "true"
        tag: service.caddy
    labels:
      logging: promtail
      logging_jobname: containerlogs

volumes:
  caddy_data: